# Generated by Django 4.0.5 on 2022-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('commit_sha', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('commit_message', models.TextField(blank=True, null=True)),
                ('commit_author_email', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_committer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_committer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('commit_author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_stable_status', models.IntegerField(blank=True, null=True)),
                ('repo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'git_commits',
            },
        ),
    ]
