# Generated by Django 4.0.5 on 2022-09-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitcommits',
            options={'managed': False},
        ),
    ]
