# Generated by Django 4.0.5 on 2022-09-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_alter_gitcommits_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitcommits',
            options={},
        ),
    ]
